{
 "title": "webcrawler-metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Akka Actors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mailbox SIze: All",
   "type": "timeseries",
   "description": "Tracks the behavior of an Actor's mailbox size.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"akka.actor.mailbox-size\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_start\", \"_stop\", \"_time\" \"path\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Actor processing time ",
   "type": "timeseries",
   "description": "Tracks the time taken for the actor to process the receive function.",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"akka.actor.processing-time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_start\", \"_stop\", \"_time\" \"path\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Processed messages: System",
   "type": "gauge",
   "description": "Counts the number of processed messages in an Actor System.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"akka.system.processed-messages\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"tracked\"] == \"true\")\n  |> distinct()\n  |> yield(name: \"distinct\")"
    }
   ]
  },
  {
   "title": "Worker Actors",
   "type": "timeseries",
   "description": "Number of worker actors",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"akka.group.members\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"group\", \"_value\", \"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "In-Memory Cache (Caffeine)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cache.web-crawler-cache.eviction.weight\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_start\", \"_stop\", \"_time\" \"eviction.cause\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cache.web-crawler-cache.hits\" or r[\"_measurement\"] == \"cache.web-crawler-cache.misses\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_measurement\", \"_field\", \"_value\", \"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm.memory.max\" or r[\"_measurement\"] == \"jvm.memory.free\" or r[\"_measurement\"] == \"jvm.memory.used\" or r[\"_measurement\"] == \"jvm.memory.committed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"region\"] == \"heap\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_start\", \"_stop\", \"_time\" \"_measurement\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm.memory.max\" or r[\"_measurement\"] == \"jvm.memory.free\" or r[\"_measurement\"] == \"jvm.memory.used\" or r[\"_measurement\"] == \"jvm.memory.committed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"region\"] == \"non-heap\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_start\", \"_stop\", \"_time\" \"_measurement\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"webcrawler-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm.threads.total\" or r[\"_measurement\"] == \"jvm.threads.states\" or r[\"_measurement\"] == \"jvm.threads.peak\" or r[\"_measurement\"] == \"jvm.threads.daemon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_measurement\", \"_value\", \"_start\", \"_stop\", \"_time\", \"state\"])\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}