apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    basicAuth: false
    url: http://influxdb:8086
    secureJsonData:
      token: ${DS_INFLUXDB_API_KEY}
    jsonData:
      version: Flux
      organization: ${DS_INFLUXDB_ORGANIZATION}
      defaultBucket: ${DS_INFLUXDB_BUCKET}
      timeInterval: 10s